// lib/knowledge.js
// Add your healthcare Q&A pairs or facts here

export const healthcareKnowledgeBase = [
  { question: "What are the symptoms of COVID-19?", answer: "Common symptoms include fever, cough, shortness of breath, fatigue, muscle aches, loss of taste or smell, sore throat, and headache. Severe cases may experience difficulty breathing, chest pain, or confusion." },
  { question: "How to lower blood pressure naturally?", answer: "Reduce sodium intake, exercise regularly, maintain healthy weight, limit alcohol, eat potassium-rich foods, manage stress, and quit smoking." },
  { question: "What causes headaches?", answer: "Headaches can be caused by stress, tension, dehydration, eye strain, sinus issues, caffeine withdrawal, or underlying medical conditions." },
  { question: "How to get rid of a sore throat?", answer: "Gargle with salt water, stay hydrated, use throat lozenges, drink warm liquids, use a humidifier, and rest your voice." },
  { question: "What is a normal body temperature?", answer: "The average normal body temperature is 98.6°F (37°C), but it can range from 97°F (36.1°C) to 99°F (37.2°C)." },
  { question: "How to stop coughing?", answer: "Stay hydrated, use cough drops, try honey, use a humidifier, avoid irritants, and consider over-the-counter cough medicine." },
  { question: "What causes dizziness?", answer: "Inner ear problems, low blood pressure, dehydration, anxiety, medication side effects, or underlying health conditions." },
  { question: "How to reduce fever?", answer: "Stay hydrated, rest, use over-the-counter fever reducers like acetaminophen or ibuprofen, and use cool compresses." },
  { question: "What are the signs of dehydration?", answer: "Thirst, dry mouth, fatigue, dark urine, dizziness, confusion, and decreased urine output." },
  { question: "How to treat a cold?", answer: "Rest, stay hydrated, use saline nasal spray, gargle salt water, use over-the-counter cold medicines, and eat chicken soup." },
  { question: "What causes fatigue?", answer: "Lack of sleep, poor diet, stress, anemia, thyroid issues, depression, or chronic illnesses." },
  { question: "How to boost immune system?", answer: "Eat balanced diet, exercise regularly, get enough sleep, manage stress, stay hydrated, and avoid smoking." },
  { question: "What are the symptoms of flu?", answer: "Fever, chills, cough, sore throat, runny nose, muscle aches, headaches, and fatigue." },
  { question: "How to relieve sinus pressure?", answer: "Use saline nasal spray, apply warm compresses, use steam inhalation, stay hydrated, and consider decongestants." },
  { question: "What causes nausea?", answer: "Motion sickness, pregnancy, food poisoning, medications, migraines, or gastrointestinal issues." },
  { question: "How to treat allergies?", answer: "Avoid allergens, use antihistamines, nasal corticosteroids, decongestants, and consider allergy shots." },
  { question: "What are the signs of vitamin deficiency?", answer: "Fatigue, weakness, pale skin, hair loss, strange cravings, tingling sensations, and vision changes." },
  { question: "How to improve sleep quality?", answer: "Maintain regular sleep schedule, create comfortable environment, limit screen time before bed, avoid caffeine, and exercise regularly." },
  { question: "What causes heart palpitations?", answer: "Stress, anxiety, exercise, caffeine, nicotine, fever, hormonal changes, or heart conditions." },
  { question: "How to reduce inflammation?", answer: "Eat anti-inflammatory foods (berries, fatty fish, broccoli), exercise, manage stress, and get enough sleep." },
  { question: "What is diabetes?", answer: "A chronic condition where the body cannot properly process glucose, leading to high blood sugar levels." },
  { question: "How to manage type 2 diabetes?", answer: "Monitor blood sugar, eat balanced diet, exercise regularly, take medications as prescribed, and maintain healthy weight." },
  { question: "What are the symptoms of high cholesterol?", answer: "Typically no symptoms, but can lead to chest pain, heart attack, stroke, or peripheral artery disease." },
  { question: "How to control asthma?", answer: "Use inhalers as prescribed, avoid triggers, monitor breathing, and have an asthma action plan." },
  { question: "What causes arthritis?", answer: "Wear and tear of joints, autoimmune disorders, infections, or genetic factors." },
  { question: "How to manage chronic pain?", answer: "Physical therapy, medications, exercise, stress management, and alternative therapies like acupuncture." },
  { question: "What is hypertension?", answer: "High blood pressure, a condition where the force of blood against artery walls is too high." },
  { question: "How to prevent heart disease?", answer: "Healthy diet, regular exercise, maintain healthy weight, don't smoke, and manage stress." },
  { question: "What are the signs of thyroid problems?", answer: "Fatigue, weight changes, mood swings, hair loss, temperature sensitivity, and heart rate changes." },
  { question: "How to live with fibromyalgia?", answer: "Gentle exercise, stress reduction, good sleep habits, pain management, and support groups." },
  { question: "What causes migraines?", answer: "Genetic factors, hormonal changes, stress, certain foods, weather changes, and sensory stimuli." },
  { question: "How to manage IBS?", answer: "Dietary changes, stress management, regular exercise, and medications for symptoms." },
  { question: "What is COPD?", answer: "Chronic Obstructive Pulmonary Disease, a group of lung diseases that block airflow and make breathing difficult." },
  { question: "How to prevent stroke?", answer: "Control blood pressure, manage diabetes, quit smoking, exercise, and maintain healthy diet." },
  { question: "What are the symptoms of lupus?", answer: "Fatigue, joint pain, rash, fever, and organ inflammation." },
  { question: "How to manage depression?", answer: "Therapy, medication, exercise, social support, and healthy lifestyle changes." },
  { question: "What causes anxiety disorders?", answer: "Genetics, brain chemistry, personality, and life events." },
  { question: "How to treat acid reflux?", answer: "Dietary changes, weight loss, elevation of head during sleep, and medications." },
  { question: "What is osteoporosis?", answer: "A condition where bones become weak and brittle, increasing fracture risk." },
  { question: "How to prevent kidney stones?", answer: "Stay hydrated, limit sodium, reduce animal protein, and eat calcium-rich foods." },
  { question: "When to go to ER for chest pain?", answer: "If chest pain is severe, radiates to arm/jaw, accompanied by shortness of breath, sweating, or nausea." },
  { question: "What are signs of heart attack?", answer: "Chest pain, shortness of breath, nausea, lightheadedness, and pain in arm/neck/jaw." },
  { question: "How to perform CPR?", answer: "Call 911, push hard and fast in center of chest, 100-120 compressions per minute." },
  { question: "When to seek emergency care for fever?", answer: "Fever above 103°F, lasting more than 3 days, or with severe symptoms." },
  { question: "What are symptoms of stroke?", answer: "Face drooping, arm weakness, speech difficulty, sudden confusion, vision problems." },
  { question: "How to treat burns?", answer: "Cool with running water, cover with sterile dressing, don't break blisters, seek medical help for severe burns." },
  { question: "When to worry about abdominal pain?", answer: "Severe pain, fever, vomiting blood, bloody stools, or pain lasting more than a few days." },
  { question: "What are signs of allergic reaction?", answer: "Hives, swelling, difficulty breathing, dizziness, rapid pulse." },
  { question: "How to stop bleeding?", answer: "Apply direct pressure, elevate injured area, use clean cloth, and seek medical help if severe." },
  { question: "When to go to hospital for breathing problems?", answer: "Severe shortness of breath, blue lips/fingernails, chest pain, or confusion." },
  // ...continue with all remaining Q&A pairs up to 200...
];
